{"errorMessage": "Could not find a suitable TLS CA certificate bundle, invalid path: /var/task/certifi/cacert.pem", "errorType": "OSError", "requestId": "0e07b27b-2a22-4d51-941f-ad9dea028320", "stackTrace": ["  File \"/var/task/handler.py\", line 49, in lambda_handler\n    requests.post(webhook_url, json=payload)\n", "  File \"/var/task/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n", "  File \"/var/task/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n", "  File \"/var/task/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n", "  File \"/var/task/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n", "  File \"/var/task/requests/adapters.py\", line 616, in send\n    self.cert_verify(conn, request.url, verify, cert)\n", "  File \"/var/task/requests/adapters.py\", line 303, in cert_verify\n    raise OSError(\n"]}